language: c
env:
    - FEATURE=Linux MAKEFILE=Makefile
#    - FEATURE=Windows MAKEFILE=Makefile.mingw CC=i586-mingw32msvc-gcc CXX=i586-mingw32msvc-g++ LD=i586-mingw32msvc-ld

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-multilib
    - sudo apt-get install -qq mingw32
    - sudo apt-get install -qq pidgin-dev

script:
    - echo "Build for $FEATURE"
    - make -f $MAKEFILE

after_script:

deploy:
    provider: releases
    apt_key: 3885bb8038c095c430c21a03233e5234206de63e
    file:
        - xmpp_muc_presence_plugin.so
#        - xmpp_muc_presence_plugin.dll
    skil_cleanup: true
    on:
        tags: true
        all_branches: true
