language: c

env:
    - FEATURE="ubuntu.12.04 64bit" MAKEFILE=Makefile TARGET=xmpp_muc_presence_plugin.so
#    - FEATURE=Windows MAKEFILE=Makefile.mingw CC=i586-mingw32msvc-gcc CXX=i586-mingw32msvc-g++ LD=i586-mingw32msvc-ld TARGET=xmpp_muc_presence_plugin.dll

before_install:
    - uname -a
    - sudo apt-get update -qq
    - sudo apt-get install -qq pidgin-dev

script:
    - echo "Build for $FEATURE"
    - make -f $MAKEFILE
    - cp "$TARGET" "$TARGET (for $FEATURE)"

after_script:

deploy:
    provider: releases
    api_key:
      secure: TmnCFTEVA4wGYUjiAD9ivD8AiyH7UOfwHn33yg/5bvQbTx5OCHWVGSUvnY7zbezIJq56lrGCQ14tJhUVRVtWxyJJXV1WBmmc1kuKeeUTOza68M7G2pHRhoJ0mO9FAaBr/62STuSfovIlSRF3kfJI+/jmxFd0aqaxc4MvV855Aew=
    file:
        - "xmpp_muc_presence_plugin.so (for ubuntu.12.04 64bit)"
    skil_cleanup: true
    on:
        tags: true
        all_branches: true
