language: c
#compiler:
#    - gcc
env:
    - FEATURE=FEATURE1
    - FEATURE=FEATURE2
#    - CC=i586-mingw32msvc-gcc CXX=i586-mingw32msvc-g++ LD=i586-mingw32msvc-ld

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-multilib
    - sudo apt-get install -qq mingw32
    - sudo apt-get install -qq pidgin-dev

script:
    - echo "begin FEATURE=$FEATURE"
    - make

after_script:
    - echo "end FEATURE=$FEATURE"
